### ISSUE TITLE
Publish latest version to Hex

### ISSUE THREAD

**Issue by durub** [mpiercy827/downstream#14]
Hi @mpiercy827, thanks for Downstream!

I would like to ask if it is possible to publish the current master to Hex.

I'm missing [this PR](https://github.com/mpiercy827/downstream/pull/12) because, without it, I'm having some trouble with the `httpoison` dependency.

I'm introducing a library which requires `httpoison ~> 1.6`. For this reason, it doesn't match downstream's `~> 1.5.0` (but would match `~> 1.5`). It's fixed by the PR, but the package hasn't been updated in Hex yet.

Could this be done?

Thank you!

**Comment by durub** [comment]
PS: no rush, I overrode the dependency for the time being, but it would be great to eventually stop overriding it, as it is one more thing to manage manually.

**Comment by mpiercy827** [comment]
Hey @durub , just published v1.0.1 on [Hex](https://hex.pm/packages/downstream/1.0.1). Thanks for the ping!

**Comment by durub** [comment]
Thank you!
